"use client";import{useMemo,useState}from"react";import{QRCodeSVG}from"qrcode.react";
type Member={id:number;name:string;upi:string;account?:boolean;amount:number};
const friends=[{id:101,name:"Aarav",upi:"aarav@upi",account:true},{id:102,name:"Riya",upi:"riya@upi",account:true},{id:103,name:"Rahul",upi:"rahul@upi",account:true}];
const money=(n:number)=>n.toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
export default function Home(){const[page,setPage]=useState<"home"|"split"|"account">("home"),[step,setStep]=useState(1),[bill,setBill]=useState("Coffee"),[myUpi,setMyUpi]=useState("suman@upi"),[total,setTotal]=useState("10"),[type,setType]=useState<"equal"|"custom">("equal"),[members,setMembers]=useState<Member[]>([{id:1,name:"You",upi:"suman@upi",account:true,amount:0}]),[toast,setToast]=useState("");
const pop=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),1700)};
const equal=useMemo(()=>{const n=members.length;return n?Number(total||0)/n:0},[total,members.length]);
const redistribute=(list:Member[],sum=Number(total||0))=>list.map(m=>({...m,amount:sum/list.length}));
const updateTotal=(v:string)=>{setTotal(v.replace(/[^0-9.]/g,""))};
const addFriend=(f:any)=>{if(members.some(m=>m.id===f.id))return;const list=[...members,{...f,amount:0}];setMembers(type==="equal"?redistribute(list):list)};
const addGuest=()=>{const id=Date.now(),list=[...members,{id,name:"Person "+members.length,upi:"",account:false,amount:0}];setMembers(type==="equal"?redistribute(list):list)};
const remove=(id:number)=>{const list=members.filter(m=>m.id!==id);setMembers(list.length&&type==="equal"?redistribute(list):list)};
const changeName=(id:number,name:string)=>setMembers(members.map(m=>m.id===id?{...m,name}:m));
const changeAmount=(id:number,v:string)=>setMembers(members.map(m=>m.id===id?{...m,amount:Number(v)||0}:m));
const setEqual=()=>{setType("equal");setMembers(redistribute(members))};
const customValid=Math.abs(members.reduce((s,m)=>s+m.amount,0)-Number(total||0))<0.000001;
const createBill=()=>{if(!bill.trim()||!myUpi.trim()||Number(total)<=0)return pop("Please complete the bill details");if(type==="custom"&&!customValid)return pop("Custom amounts must equal the total");setStep(2)};
return <main><header><div className="brand" onClick={()=>setPage("home")}><b>U</b><strong>UPI<span>Circle</span></strong></div><nav><button className={page==="home"?"navActive":""} onClick={()=>setPage("home")}>Home</button><button className={page==="split"?"navActive":""} onClick={()=>{setPage("split");setStep(1)}}>Create Split</button><button onClick={()=>pop("History is coming next")}>History</button></nav><button className="profile">SN</button></header>
{page==="home"?<section className="hero"><div><div className="eyebrow"><span>●</span> BUILT FOR FRIEND GROUPS <b>UPI-FIRST</b></div><h1>Split money.<br/><i>Not friendships.</i></h1><p>Make a shared bill, add your circle, and create a personal UPI payment bill for every member.</p><div className="heroTags"><span>₹ Exact splits</span><span>⚡ No signup required</span><span>⌁ Shareable QR bills</span></div><div className="actions"><button className="primary" onClick={()=>{setPage("split");setStep(1)}}>Create a split →</button><button className="secondary" onClick={()=>setPage("account")}>Create an account</button></div><div className="heroStats"><div><strong>2.50</strong><span>Exact decimals</span></div><div><strong>1 → 4</strong><span>One bill, many people</span></div><div><strong>QR</strong><span>Ready to share</span></div></div></div><div className="mock"><div className="glow"/><div className="floatBadge badgeTop"><span>✓</span> Exact split</div><div className="floatBadge badgeBottom"><span>↗</span> Ready to share</div><div className="phone"><div className="phoneTop"><span></span><span></span><span></span></div><small>UPI CIRCLE</small><h2>Coffee</h2><span>4 people · ₹10.00</span>{[["S","Suman","₹2.50"],["A","Aarav","₹2.50"],["R","Riya","₹2.50"],["R","Rahul","₹2.50"]].map((x,i)=><div className="mini" key={i}><b className={"av a"+i}>{x[0]}</b><div><strong>{x[1]}</strong><small>{x[2]} to pay</small></div><em>QR</em></div>)}</div></div></section>
:page==="account"?<section className="account"><div className="card accountCard"><label>UPI CIRCLE ACCOUNT</label><h1>Create your account</h1><p>Save friends, circles, bills and payment history across devices.</p><input placeholder="Your name"/><input placeholder="Email address"/><input placeholder="Create password" type="password"/><button className="primary" onClick={()=>pop("Account creation will be connected next")}>Create account</button><button className="wideBtn" onClick={()=>setPage("home")}>Back to home</button></div></section>
:<section className="work"><div className="head"><div><label>{step===1?"STEP 1 · BILL DETAILS":step===2?"STEP 2 · YOUR CIRCLE":"STEP 3 · PERSONAL BILLS"}</label><h1>{step===1?"Create your split":step===2?"Add your circle":"Your bills are ready"}</h1><p>{step===1?"Set the bill, your UPI address, amount and split method.":step===2?"Add friends from your account or add anyone by nickname.":"Every member gets a separate QR bill with their exact amount."}</p></div><div className="steps">{[1,2,3].map(n=><b className={step>=n?"on":""} key={n}>{step>n?"✓":n}</b>)}</div></div>
{step===1&&<div className="card grid"><label>Billing name<input value={bill} placeholder="e.g. Coffee" onChange={e=>setBill(e.target.value)}/></label><label>Your UPI address<input value={myUpi} placeholder="yourname@upi" onChange={e=>setMyUpi(e.target.value)}/></label><label>Amount to split<div className="money">₹<input value={total} onChange={e=>updateTotal(e.target.value)}/></div></label><label className="wide">Split type<div className="choices"><button className={type==="equal"?"chosen":""} onClick={()=>setEqual()}><strong>Equal split</strong><small>Automatically divide equally as people are added or removed.</small></button><button className={type==="custom"?"chosen":""} onClick={()=>{setType("custom");setMembers(members.map(m=>({...m,amount:equal})))}}><strong>Custom split</strong><small>You decide the exact amount for every member.</small></button></div></label><div className="foot wide"><small>Decimals are supported — e.g. ₹10 ÷ 4 = ₹2.50.</small><button className="primary" onClick={createBill}>Continue →</button></div></div>}
{step===2&&<div className="card"><div className="memberHead"><div><b>{members.length} {members.length===1?"person":"people"}</b><small>Amounts update automatically in Equal split.</small></div><div className="addBtns"><button className="add" onClick={addGuest}>＋ Add person</button>{type==="equal"&&<button className="reset" onClick={setEqual}>↻ Split equally</button>}</div></div><div className="friendBox"><strong>Add from your circle</strong><div className="friendList">{friends.map(f=><button key={f.id} className="friend" onClick={()=>addFriend(f)}><b className="av a1">{f.name[0]}</b><span><strong>{f.name}</strong><small>{f.upi} · Account</small></span><em>＋</em></button>)}</div><small>Friends with UPI Circle accounts can be selected from your saved circle.</small></div>{members.map((m,i)=><div className="member" key={m.id}><b className={"av a"+i}>{m.name[0]}</b><div className="memberInfo"><input className="nickname" value={m.name} onChange={e=>changeName(m.id,e.target.value)}/><small>{m.id===1?myUpi:(m.upi||"No UPI added")}</small></div>{type==="custom"&&<label>Amount<input value={m.amount} onChange={e=>changeAmount(m.id,e.target.value)}/></label>}<button className="delete" onClick={()=>remove(m.id)} title="Delete person">Delete</button></div>)}<div className="summary"><div><small>Total</small><strong>₹{money(Number(total)||0)}</strong></div><div><small>Per person</small><strong>₹{money(type==="equal"?equal:0)}</strong></div><div><small>Members</small><strong>{members.length}</strong></div></div>{type==="custom"&&<div className={customValid?"valid":"invalid"}>{customValid?"✓ Custom amounts match the bill total.":"⚠ Custom amounts must add up exactly to the bill total."}</div>}<div className="foot"><button onClick={()=>setStep(1)}>Back</button><button className="primary" onClick={()=>{if(type==="custom"&&!customValid)return pop("Fix custom amounts first");setStep(3)}}>Generate bills →</button></div></div>}
{step===3&&<div><div className="billTop"><button onClick={()=>setStep(2)}>← Edit circle</button><button className="primary" onClick={()=>pop("Share options are ready")}>Share all bills</button></div><div className="personalBills">{members.map((m,i)=>{const amt=type==="equal"?equal:m.amount;const uri=`upi://pay?pa=${encodeURIComponent(myUpi)}&pn=${encodeURIComponent(bill)}&am=${amt.toFixed(2)}&cu=INR`;return <div className="card personal" key={m.id}><div className="billTitle"><div><span className="live">● READY</span><h2>{m.name}'s bill</h2><small>{bill} · Pay to {myUpi}</small></div><strong>₹{money(amt)}</strong></div><div className="billBody"><div><p>This QR is for <b>{m.name}</b>.</p><small>Amount is locked to exactly ₹{money(amt)}. They can scan it with a UPI app.</small><button className="wideBtn" onClick={()=>pop(`Share bill with ${m.name}`)}>Share {m.name}'s QR bill</button></div><div className="qr"><QRCodeSVG value={uri} size={155} level="M"/></div></div></div>})}</div></div>}</section>}<footer>© 2026 UPI Circle · Split. Scan. Done. · Prototype v0.2</footer>{toast&&<div className="toast">✓ {toast}</div>}</main>}